version: 2.1

jobs:
  build:
    docker:
      - image: golang:latest

    steps:
      - checkout

      # Run tests in the 'test' directory
      - run:
          name: Run tests
          command: go test ./test/...
